# Site's name:
name: 'Activate PDX'

# Site's tagline:
tagline: "Portland's Progressive Calendar"

# Site's URL with trailing slash:
url: 'http://activatepdx.org/'

# Default timezone, run "rake -D time" for information on how to display known timezones:
timezone: 'Pacific Time (US & Canada)'

# Precompile additional theme assets (theme.js, theme.css, and images already included):
precompile_assets:
  - 'mobile.css'
  - 'print.css'
  - 'site.css'
  - 'fullcalendar.css'
  - 'fullcalendar.min.js'

# Google map to display on /venues page:
venues_google_map_options:
  # Zoom magnification level:
  zoom: 12
  # Center of the map, in latitude and longitude:
  center: [45.518493, -122.660737]

# Array of tag names to exclude from tag cloud:
tagcloud_exclusions:
  - ostartupskey
  - tvg
